name: users_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_map: ^6.0.1
  flutter_riverpod: ^2.4.5
  intl: ^0.18.1
  lottie: ^2.7.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/lotties_animation/
  #   - images/a_dot_ham.jpeg
